version: '3.1'
name: Rozdel-A-Panuj-DB

services:

  mongo:
    image: mongo:6
    container_name: mongo-db
    env_file: .env-mongo
    restart: always
    ports:
      - 3002:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Aa123456
      MONGO_INITDB_DATABASE: Rozdel-A-Panuj-DB
    volumes:
      - ./db:/docker-entrypoint-initdb.d