version: '3.1'
name: Rozdel-A-Panuj-DB

services:

  mongo:
    image: mongo:6
    container_name: mongo-db
    restart: always
    ports:
      - 3002:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Aa123456

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: Aa123456
      ME_CONFIG_MONGODB_URL: mongodb://root:Aa123456@mongo:3002/