name: rozdel-a-panuj-db

services:
  mongo:
    image: mongo:6
    container_name: mongo-db
    restart: always
    ports:
      - 3002:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Aa123456
      MONGO_INITDB_DATABASE: db_rozdel_a_panuj
    volumes:
      - ./init:/docker-entrypoint-initdb.d/

  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'

  mongo-express:
    image: mongo-express:1.0.0-20
    restart: always
    depends_on:
        mongo:
          condition: service_started
    ports:
     - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: Aa123456
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: Aa123456
      ME_CONFIG_MONGODB_URL: mongo://root:Aa123456@localhost:3002/db_rozdel_a_panuj?authSource=admin

